services:
  database:
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  hihihiha:
    image: hihihiha
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/static
    ports:
      - "8000:8000"
    networks:
      - default
  frontend:
    image: frontend
    build:
      ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - hihihiha
    env_file:
      - .env
    networks:
      - default
  
        
networks:
  default:
    driver: bridge