services:
  database:
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  hihihiha:
    image: hihihiha
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/static
    ports:
      - "8000:8000"
    networks:
      - default
  frontend:
    image: frontend
    build:
      ./my-pwa-app
    ports:
      - "3000:3000"
    depends_on:
      - hihihiha
    env_file:
      - .env
    networks:
      - default
  gitlab:
    image: gitlab/gitlab-ee:<version>-ee.0
    container_name: gitlab
    restart: always
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        # Add any other gitlab.rb configuration here, each on its own line
#        external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
        
networks:
  default:
    driver: bridge